# PB55
```
Create a Pandas DataFrame from the following table and write code to remove all rows from this table containing at least one 
NaN value
```

In [1]:
import pandas as pd
import numpy as np

In [7]:
data = {
    'name':["william","Emma","Sofia","Markus","Edward","thomus","ethan",np.nan,"Arun","Anika","paulo"],
    'region':[np.nan,'North','East',np.nan,'West','West','South',np.nan,'West','East','South'],
    'Sales':[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000],
    'expenses':[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000]
}
df = pd.DataFrame(data)
df

       name region    Sales  expenses
0   william    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    thomus   West  72000.0   39000.0
6     ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    paulo  South  67000.0   45000.0

In [10]:
df1=df.dropna()

In [11]:
df1

      name region    Sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   thomus   West  72000.0   39000.0
6    ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   paulo  South  67000.0   45000.0

In [12]:
df

       name region    Sales  expenses
0   william    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    thomus   West  72000.0   39000.0
6     ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    paulo  South  67000.0   45000.0

In [15]:
# pb 57
df.dropna(how='all')

       name region    Sales  expenses
0   william    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    thomus   West  72000.0   39000.0
6     ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    paulo  South  67000.0   45000.0

#59

NameError: name 'remove_outliers_iqr' is not defined