# Unit -3 - Feature creation & Feature Transformantion

In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    'A':[10,20,30,40,50,60,70,80],
    'B':[1,3,2,4,5,6,7,8]
}
df = pd.DataFrame(data)
print(df)

    A  B
0  10  1
1  20  3
2  30  2
3  40  4
4  50  5
5  60  6
6  70  7
7  80  8

In [5]:
df

    A  B
0  10  1
1  20  3
2  30  2
3  40  4
4  50  5
5  60  6
6  70  7
7  80  8

In [6]:
df['C']=df['A']+df['B']

In [7]:
df

    A  B   C
0  10  1  11
1  20  3  23
2  30  2  32
3  40  4  44
4  50  5  55
5  60  6  66
6  70  7  77
7  80  8  88

In [8]:
df['C']+4

0    15
1    27
2    36
3    48
4    59
5    70
6    81
7    92
Name: C, dtype: int64

In [9]:
df['Result']= np.where(df['C']>50,'Pass','Fail')
df

    A  B   C Result
0  10  1  11   Fail
1  20  3  23   Fail
2  30  2  32   Fail
3  40  4  44   Fail
4  50  5  55   Pass
5  60  6  66   Pass
6  70  7  77   Pass
7  80  8  88   Pass

In [10]:
df["Grade"]=np.where(df['C']>80,'A',
                     np.where(df["C"]>60,'B',
                              np.where(df['C']>50,'C',
                                       np.where(df['C']>40,'D','E'))))
df

    A  B   C Result Grade
0  10  1  11   Fail     E
1  20  3  23   Fail     E
2  30  2  32   Fail     E
3  40  4  44   Fail     D
4  50  5  55   Pass     C
5  60  6  66   Pass     B
6  70  7  77   Pass     B
7  80  8  88   Pass     A

In [11]:
data = {
    'Marks':[23,21,18,15,16,14,12,23,12,10,11,12],
    'Gender':['Male','Female','Male','Female','Male','Female','Male','Female','Male','Female','Male','Female']
}
df = pd.DataFrame(data)
df

    Marks  Gender
0      23    Male
1      21  Female
2      18    Male
3      15  Female
4      16    Male
5      14  Female
6      12    Male
7      23  Female
8      12    Male
9      10  Female
10     11    Male
11     12  Female

## ONE-hot Encoding

In [12]:
pd.get_dummies(df,drop_first=True)

    Marks  Gender_Male
0      23         True
1      21        False
2      18         True
3      15        False
4      16         True
5      14        False
6      12         True
7      23        False
8      12         True
9      10        False
10     11         True
11     12        False

# Train-Validation split

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
!python --version

Python 3.13.5

In [15]:
x = df['Marks']
y = df['Gender']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [16]:
x_train

5     14
11    12
8     12
10    11
3     15
1     21
0     23
4     16
9     10
Name: Marks, dtype: int64

In [17]:
pip install dash

Requirement already satisfied: dash in c:\users\vdp87\anaconda3\lib\site-packages (4.1.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: Flask<3.2,>=1.0.4 in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (3.1.0)
Requirement already satisfied: Werkzeug<3.2 in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (3.1.3)
Requirement already satisfied: plotly>=5.0.0 in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (8.5.0)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (4.12.2)
Requirement already satisfied: requests in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in c:\users\vdp87\anaconda3\lib\site-packages (from dash) (72.1.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\vdp87\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.2 in c:\users\vdp87\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\vdp87\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.9 in c:\users\vdp87\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\vdp87\anaconda3\lib\site-packages (from Werkzeug<3.2->dash) (3.0.2)
Requirement already satisfied: colorama in c:\users\vdp87\anaconda3\lib\site-packages (from click>=8.1.3->Flask<3.2,>=1.0.4->dash) (0.4.6)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\vdp87\anaconda3\lib\site-packages (from plotly>=5.0.0->dash) (9.0.0)
Requirement already satisfied: packaging in c:\users\vdp87\anaconda3\lib\site-packages (from plotly>=5.0.0->dash) (24.2)
Requirement already satisfied: zipp>=3.20 in c:\users\vdp87\anaconda3\lib\site-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\vdp87\anaconda3\lib\site-packages (from requests->dash) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vdp87\anaconda3\lib\site-packages (from requests->dash) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vdp87\anaconda3\lib\site-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vdp87\anaconda3\lib\site-packages (from requests->dash) (2025.4.26)

In [28]:
        import dash
from dash import html,dcc
import plotly.express as px
import plotly.io as pio
pio.renderers.default='browser'
data ={
    'Player':['Kohli','Rohit','Hardik'],
    'Runs':[78,65,92]
}
df = pd.DataFrame(data)
fig = px.bar(df, x='Player', y='Runs', title='Player Runs')
app =dash.Dash(__name__)
app.layout = html.Div([html.H1('Simple Dash App'),
                      html.H6('Plotly Example')])
if __name__=='__main__':
    app.run(port=8057)

In [18]:
df = pd.read_csv('ipl-matches.csv')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [20]:
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [21]:
df.replace(['Delhi Daredevils','Kings XI Punjab','Rising Pune Supergiants'],[' Delhi Capitals',' Punjab Kings',' Rising Pune Supergiant'])

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Capitals,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Capitals,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Punjab Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [22]:
df.groupby('Season')['WinningTeam'].apply(lambda x:x.value_counts().head(1))

Season
2007/08  Rajasthan Royals         13
2009     Delhi Daredevils         10
2009/10  Mumbai Indians           11
2011     Chennai Super Kings      11
2012     Kolkata Knight Riders    12
2013     Mumbai Indians           13
2014     Kings XI Punjab          12
2015     Mumbai Indians           10
2016     Sunrisers Hyderabad      11
2017     Mumbai Indians           12
2018     Chennai Super Kings      11
2019     Mumbai Indians           11
2020/21  Mumbai Indians           11
2021     Chennai Super Kings      11
2022     Gujarat Titans           12
Name: WinningTeam, dtype: int64

In [23]:
df.groupby('WinningTeam')['Player_of_Match'].nunique().sort_values(ascending=False)

WinningTeam
Kolkata Knight Riders          44
Mumbai Indians                 43
Kings XI Punjab                42
Rajasthan Royals               41
Delhi Daredevils               39
Chennai Super Kings            39
Sunrisers Hyderabad            36
Royal Challengers Bangalore    36
Deccan Chargers                19
Delhi Capitals                 16
Pune Warriors                  11
Punjab Kings                   10
Gujarat Titans                  9
Gujarat Lions                   7
Rising Pune Supergiant          7
Lucknow Super Giants            6
Kochi Tuskers Kerala            4
Rising Pune Supergiants         3
Name: Player_of_Match, dtype: int64

In [24]:
df.groupby('TossDecision',as_index=False)['WinningTeam'].value_counts(ascending=False)

   TossDecision                  WinningTeam  count
0           bat          Chennai Super Kings     59
1           bat               Mumbai Indians     52
2           bat        Kolkata Knight Riders     42
3           bat             Rajasthan Royals     40
4           bat  Royal Challengers Bangalore     35
5           bat             Delhi Daredevils     29
6           bat          Sunrisers Hyderabad     25
7           bat              Kings XI Punjab     24
8           bat              Deccan Chargers     14
9           bat                Pune Warriors      9
10          bat               Delhi Capitals      8
11          bat               Gujarat Titans      5
12          bat                Gujarat Lions      2
13          bat         Lucknow Super Giants      2
14          bat                 Punjab Kings      2
15          bat      Rising Pune Supergiants      2
16        field               Mumbai Indians     79
17        field  Royal Challengers Bangalore     74
18        field        Kolkata Knight Riders     72
19        field              Kings XI Punjab     64
20        field          Chennai Super Kings     62
21        field             Rajasthan Royals     56
22        field          Sunrisers Hyderabad     50
23        field             Delhi Daredevils     38
24        field               Delhi Capitals     28
25        field              Deccan Chargers     15
26        field                Gujarat Lions     11
27        field                 Punjab Kings     11
28        field       Rising Pune Supergiant     10
29        field               Gujarat Titans      7
30        field         Lucknow Super Giants      7
31        field         Kochi Tuskers Kerala      6
32        field                Pune Warriors      3
33        field      Rising Pune Supergiants      3

In [25]:
df.groupby('TossDecision',as_index=False)['WinningTeam'].value_counts().sort_values(by='count',ascending=False).rename({'count':'wins'})

   TossDecision                  WinningTeam  count
16        field               Mumbai Indians     79
17        field  Royal Challengers Bangalore     74
18        field        Kolkata Knight Riders     72
19        field              Kings XI Punjab     64
20        field          Chennai Super Kings     62
0           bat          Chennai Super Kings     59
21        field             Rajasthan Royals     56
1           bat               Mumbai Indians     52
22        field          Sunrisers Hyderabad     50
2           bat        Kolkata Knight Riders     42
3           bat             Rajasthan Royals     40
23        field             Delhi Daredevils     38
4           bat  Royal Challengers Bangalore     35
5           bat             Delhi Daredevils     29
24        field               Delhi Capitals     28
6           bat          Sunrisers Hyderabad     25
7           bat              Kings XI Punjab     24
25        field              Deccan Chargers     15
8           bat              Deccan Chargers     14
26        field                Gujarat Lions     11
27        field                 Punjab Kings     11
28        field       Rising Pune Supergiant     10
9           bat                Pune Warriors      9
10          bat               Delhi Capitals      8
30        field         Lucknow Super Giants      7
29        field               Gujarat Titans      7
31        field         Kochi Tuskers Kerala      6
11          bat               Gujarat Titans      5
32        field                Pune Warriors      3
33        field      Rising Pune Supergiants      3
14          bat                 Punjab Kings      2
15          bat      Rising Pune Supergiants      2
12          bat                Gujarat Lions      2
13          bat         Lucknow Super Giants      2

In [26]:
df.groupby('Venue')['WinningTeam'].value_counts(ascending=False).head(5)

Venue                 WinningTeam
Arun Jaitley Stadium  Delhi Capitals         4
                      Delhi Daredevils       4
                      Sunrisers Hyderabad    2
                      Chennai Super Kings    1
                      Kings XI Punjab        1
Name: count, dtype: int64